version: "3.9"

services:

  stock-data-integration:
    build: ./stock-data/stock-data-integration
    ports:
    - '8080:8080'

#  stock-data-persistence:
#    build: ./stock-data/stock-data-persistence
#    ports:
#    - '8091:8080'

  web:
    build: ./stockprediction
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - stockprediction/.env.dev

#  db:
#    image: mysql:8.0.22
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'stock_db'
#      MYSQL_ROOT_PASSWORD: 'root'
#    ports:
#      - '3306:3306'
#    expose:
#      - '3306'
