server:
  port: 8080

com:
  zwang:
    stock:
      apiKey: "DVAO0LCOZGXDO1M6" # J9N9TGT6JVB5C49IXYs,ENNOVS510HEOLGOZ,DZBQ2P5IC6BGSES8,Y38LYEZOY3ZJLN,U1J03V46QS61CZ2P,H98G9NQPKJAKUT7,FB2D8M91YQ6XRXI4,83XAKNOV7ZK5SFVE,P2G84U2JZZK8XKBV,0KJJJ6YYZZI1BEFJ,ISQ2R3Q9NZMSJBDN,X0YGPIOTUZUKB49G,VL86KQIQOII25NKB2,MHEXKOIRYDA6DJBW,M9KJ8IWO1BKRQ5KD,EZ7HBBJT3W5XICL3
      timeout: 60000
      outputSize: "full" # compact
