# Generated by Django 3.1.4 on 2020-12-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAdjusted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=10, max_digits=19)),
                ('high', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low', models.DecimalField(decimal_places=10, max_digits=19)),
                ('close', models.DecimalField(decimal_places=10, max_digits=19)),
                ('adjustedClose', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volume', models.IntegerField(null=True)),
                ('dividendAmount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('splitCoefficient', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
